### ISSUE TITLE
container builds failing for github and azure

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneapi-ci#16]
They are too big for the host machine. Should we disable these builds?

**Comment by mmzakhar** [comment]
The PR to temporarily disable the affected builds has been created. I'm investigating the root cause behind the failures.

**Comment by mmzakhar** [comment]
The linked PR fixes the issue.
Microsoft-hosted agents only have 10 GB of disk space available for job, so a smaller host-OS image needs to be used not to exceed it, especially in combination with large container.
