### ISSUE TITLE
Include a terms of use paragraph in README?

### ISSUE THREAD

**Issue by Huite** [oneapi-src/oneapi-ci#38]
Greetings all,

This seems like a wonderful resource to get Intel compilers working for open source development. I'd like to suggest adding a paragraph regarding the terms of use. You currently point to a CC-BY-4.0 and MIT license under the license heading, but this is insufficiently clear to me. Recalling the adage of:

> If something seems too good to be true, it probably is.

So I wasn't sure, and I checked this page:
https://software.intel.com/content/www/us/en/develop/articles/qualify-for-free-software.html

And a recent EULA:
https://software.intel.com/content/dam/develop/public/us/en/documents/intel-end-user-license-agreement-for-developer-tools-oct-2020.pdf

Which leads me to the following impressions:

* I can use excerpts from this repository to configure CI for open source software (public domain in this specific case), provided I attribute this repo
* I am allowed to install ifort on the CI machine
* I am allowed to use ifort to build a binary on the CI machine
* I am allowed to distribute binaries that were built on that CI machine

Is my understanding correct?

If my understanding is correct, then I'd suggest adding something like such a specifically worded list in the README, as well as providing a link to the EULA proper of course (if that also pleases the lawyerly types sufficiently).

**Comment by rscohn2** [comment]
Your understanding is correct on all points. We will add some text. It will probably have to be a pointer to some text on the intel site that will address the points.

**Comment by Huite** [comment]
Excellent, thank you for the prompt answer!
