### ISSUE TITLE
ICPX Examples

### ISSUE THREAD

**Issue by ax3l** [oneapi-src/oneapi-ci#40]
Hi,

thank you for this repo!

I saw in the readme that `icpx` is not yet listed as compiler but shipped and usable like `dpcpp` :)
Should it be added?

I already test against it:
- https://github.com/ECP-WarpX/WarpX/pull/1608

**Comment by mmzakhar** [comment]
Hi @ax3l.

Sure, any tool from Intel® oneAPI toolkits can be installed in a similar way and used in CI. We created a page with the list of available components: see [component listings](https://oneapi-src.github.io/oneapi-ci/)

We also extended the list of compilers in the Readme and added their invocation in the build scripts.

Thanks,
Maxim

**Comment by ax3l** [comment]
Looks great, thank you!
Closed via dd255104fc905c5faf6908ebae74687544b67880
