### ISSUE TITLE
Issue on page /index.html: Identical component listings for Windows Toolkits

### ISSUE THREAD

**Issue by marcfehling** [oneapi-src/oneapi-ci#73]
The [component listings](https://oneapi-src.github.io/oneapi-ci/) for Windows Toolkits show identical components for
- [Intel® oneAPI Base Toolkit](https://oneapi-src.github.io/oneapi-ci/#intelr-oneapi-base-toolkit)
- [Intel® oneAPI HPC Toolkit](https://oneapi-src.github.io/oneapi-ci/#intelr-oneapi-hpc-toolkit)
- [Intel® oneAPI IoT Toolkit](https://oneapi-src.github.io/oneapi-ci/#intelr-oneapi-iot-toolkit)
- [Intel® oneAPI Rendering Toolkit](https://oneapi-src.github.io/oneapi-ci/#intelr-oneapi-rendering-toolkit)

This caught my eye as `mpi` does not occur in any of these listings, and I believe this is an error. Can you double check this?

**Comment by mmzakhar** [comment]
This should be resolved now. Please double check.

**Comment by marcfehling** [comment]
Looks good to me now. Thanks!
